################################# Default configuration ###################
baseURL = "/"
title = "Goldschmiede Metallglanz"
theme = "meghna-hugo"
themesDir = "./themes"

# post pagination
paginate = "6"

# post excerpt
summaryLength = "15"

# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com

# disable language
disableLanguages = []
defaultContentLanguage = "de"

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

################### German Navigation ########################
[[Languages.de.menu.main]]
name = "Über mich"
url = "#feature"
weight = 1

[[Languages.de.menu.main]]
name = "Portfolio"
url = "#portfolio"
weight = 2

[[Languages.de.menu.main]]
name = "Kontakt"
url = "#contact"
weight = 3

[[Languages.de.menu.main]]
name = "Datenschutzerklärung"
url = "/blog/datenschutz"
weight = 4

[[Languages.de.menu.main]]
name = "Impressum"
url = "/blog/impressum"
weight = 5

############################# Default Parameters ##########################
[params]
logo = "images/logo.jpg"
# Meta data
description = "Goldschmiede Metallglanz"
author = "Goldschmiede Metallglanz"
# Google Analytics
google_analytics_id = "" # Your ID
# post share
post_share = false

# preloader
[params.preloader]
enable = false
preloader = "images/logo.jpg"

# cookies
[params.cookies]
enable = true
expire_days = 2

############################# social icons ##########################
[[params.social]]
icon = "ti-instagram" # themify icon pack : https://themify.me/themify-icons
link = "https://instagram.com/goldschmiede-metallglanz"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "https://twitter.com/multiple_green"


################################ German Language ########################
[Languages.de]
languageName = "De"
languageCode = "de-de"
contentDir = "content/de"
weight = 1
home = "Home"
copyright = "Copyright &copy; 2021 Goldschmiede Metallglanz"
